theme = "base16_transparent"

[editor]
  bufferline = "always"
  cursorline = true
  trim-final-newlines = true
  trim-trailing-whitespace = true
  true-color = true

[editor.file-picker]
  hidden = false

[editor.statusline]
  left = ["mode", "spinner", "version-control"]
  center = ["file-name", "file-modification-indicator"]
  right = ["file-type", "selections", "position", "file-encoding"]
  separator = "|"
  mode.normal = "NORMAL"
  mode.insert = "INSERT"
  mode.select = "SELECT"

[editor.whitespace.render]
  tab = "all"

[editor.indent-guides]
  render = true
  character = "â”‚"
  skip-levels = 1

[editor.lsp]
  display-messages = true
  display-inlay-hints = true

[keys.normal]
  C-t = ":toggle file-picker.git-ignore"
